# Generated by Django 6.0.2 on 2026-02-16 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tripplan",
            name="duration_days",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="tripplan",
            name="origin",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="tripplan",
            name="trip_type",
            field=models.CharField(default="Vacation", max_length=100),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="vibe",
            field=models.CharField(max_length=255),
        ),
    ]
