# Generated by Django 6.0.2 on 2026-02-16 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_tripplan_duration_days_tripplan_origin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripplan",
            name="trip_type",
        ),
        migrations.AddField(
            model_name="tripplan",
            name="arrival_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tripplan",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="duration_days",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="origin",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="vibe",
            field=models.CharField(max_length=100),
        ),
    ]
